[build]
publish = "drgpls/public"
command = "cd drgpls && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.92.0"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd drgpls &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
